server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "totallydefaultpassword"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 1 # Number of pages at 100 each
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 50MB
  path: ./logs/

  level:
    root: WARNING
    lavalink: WARNING